lint.select = [
    "F", # Flake8
    "B", # Black
    "I", # isort
    "E", # error
    "W"  # warning
]
lint.ignore = []
lint.fixable = ["ALL"]
exclude = [
    ".ruff_cache"
]
line-length = 150
indent-width = 4
target-version = "py310"

extend-include = ["*.ipynb"]

unfixable = ["F401"]
